### ISSUE TITLE
how to perform cNMF  on non-typical gene expression data

### ISSUE THREAD

**Issue by YangShi-PKU** [dylkot/cNMF#28]
HI
I want to do NMF on my single cell data. However, my data is not traditional count data, for each transcript isoform in each cell, the value is generated by: count_of_isoform1 / count_of_all_isoform_of_the_same_gene.
So it's indeed a ration between 0-1. I want to know how to use such data in cNMF. I've tried feed the "ratio matrix" to --tpm, but it throws out en error:
`Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 783, in <module>
    if args.counts.endswith('.h5ad'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 853, in <module>
    cnmf_obj.run_nmf(worker_i=args.worker_index, total_workers=args.total_workers)
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 449, in run_nmf
    run_params = load_df_from_npz(self.paths['nmf_replicate_parameters'])
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 33, in load_df_from_npz
    with np.load(filename, allow_pickle=True) as f:
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/miniconda3/envs/cnmf_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruibinxi_pkuhpc/lustre1/shiyang/APA/ICC_cnmf_out_pas_new/I02T/cnmf_tmp/I02T.nmf_params.df.npz'
Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 856, in <module>
    run_params = load_df_from_npz(cnmf_obj.paths['nmf_replicate_parameters'])
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 33, in load_df_from_npz
    with np.load(filename, allow_pickle=True) as f:
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/miniconda3/envs/cnmf_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruibinxi_pkuhpc/lustre1/shiyang/APA/ICC_cnmf_out_pas_new/I02T/cnmf_tmp/I02T.nmf_params.df.npz'
Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 883, in <module>
    cnmf_obj.k_selection_plot()
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 692, in k_selection_plot
    run_params = load_df_from_npz(self.paths['nmf_replicate_parameters'])
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 33, in load_df_from_npz
    with np.load(filename, allow_pickle=True) as f:
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/miniconda3/envs/cnmf_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruibinxi_pkuhpc/lustre1/shiyang/APA/ICC_cnmf_out_pas_new/I02T/cnmf_tmp/I02T.nmf_params.df.npz'
Traceback (most recent call last):
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 869, in <module>
    run_params = load_df_from_npz(cnmf_obj.paths['nmf_replicate_parameters'])
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/project_2019_11/NMF2/cnmf.py", line 33, in load_df_from_npz
    with np.load(filename, allow_pickle=True) as f:
  File "/home/ruibinxi_pkuhpc/lustre1/huangsiyuan/miniconda3/envs/cnmf_env/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruibinxi_pkuhpc/lustre1/shiyang/APA/ICC_cnmf_out_pas_new/I02T/cnmf_tmp/I02T.nmf_params.df.npz'
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.`
I wonder if it's because I don't give the -c (count) file to cNMF.
Could you please give some advice? Thanks

**Comment by dylkot** [comment]
Hi @YangShi-PKU,

Thanks for your interest in cNMF!

Yes you are right, the error is because cNMF expects a count matrix, even if you provide the optional TPM matrix as well. The simplest solution here would be to provide your same input matrix to both -c and --tpm input. You will also likely want to think about providing your own set of genes to the --genes-file option since it isn't clear to me that you'd want to use the same definition of over-dispersion as what you would use for counts data.

cNMF variance normalizes the selected over-dispersed genes before running NMF. Do you think that would still be appropriate for your input data?

Best,
Dylan

**Comment by YangShi-PKU** [comment]
Thanks for you suggestion Dylan!
I'll try give my matrix to both -c and --tpm. As for the genes, my values are from 0 to 1, so I guess the definition of over-dispersion for count data will not work for me. Do you have some experience on selecting over-dispersed features from values ranging from 0-1? Thanks!

Best regards,
Yang

**Comment by dylkot** [comment]
I do not, precisely. But standard-deviation might be a good place to start?

**Comment by YangShi-PKU** [comment]
Thanks for your suggestion! I'll try different processing methods and see which one could give me the most reasonable result.

Best
Yang
