### ISSUE TITLE
The consense step showing below error

### ISSUE THREAD

**Issue by honghh2018** [dylkot/cNMF#29]
Hi developer,

# python3.7
Traceback (most recent call last):
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 908, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering)
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 629, in consensus
    cl_dist = squareform(topics_dist[cl_filter, :][:, cl_filter])
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2260, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric.
Traceback (most recent call last):
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 908, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering)
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 629, in consensus
    cl_dist = squareform(topics_dist[cl_filter, :][:, cl_filter])
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2260, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric

How can i fix this issue?
Best
hanhuihong

**Comment by honghh2018** [comment]
Had advice for this issue?

**Comment by honghh2018** [comment]
Had anybody hear this issue?

**Comment by dylkot** [comment]
Hi @honghh2018 - hmm, that error can happen if you are inadvertently filtering out all of the learned gene expression program components. Can you include the full command you were using and some more details about the input data? Maybe use ```--local-density-threshold 2.00``` so that you won't be filtering out any components at all and see if it works?

**Comment by honghh2018** [comment]
Thanks the reply,

    Unfortunately, It failed too as i had adjusted the local-density-threshold with below 2.00

source Miniconda3/bin/activate cNMF-python && python -W ignore v2/bin/cNMF-master/cnmf.py consensus --output-dir result --name Luo_T --components 4 --local-density-threshold 2.00 --show-clustering
Traceback (most recent call last):
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 908, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering)
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 629, in consensus
    cl_dist = squareform(topics_dist[cl_filter, :][:, cl_filter])
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2260, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric. 
The result lying below:
![image](https://user-images.githubusercontent.com/41668708/155054864-f4ddbcb6-e9c6-4e53-af59-cbe5492a55f4.png)


the K selection was 4:
![image](https://user-images.githubusercontent.com/41668708/155054919-c2a0cfdc-3b17-4f60-863a-c9c085b05578.png)

Best

**Comment by dylkot** [comment]
Hi @honghh2018 - that's interesting, thanks for sending! It actually seems like that command worked previously because it created the expected output files? Is there anything wrong with the results when you read them in? 

It is possible that if you run cNMF multiple times with different input data or parameters, it can cause issues with cached files that are meant to speed up subsequent consensus steps.

```rm result/Luo_T/cnmf_tmp/*local_density_cache*```

might fix the problem if you need to re-run the consensus step. Or you might just re-run things from the beginning.

**Comment by honghh2018** [comment]
Hi @dylkot 
     Thanks the quick answer,
I try the de novo rerun the Luo_T sample, but unfortunately, it failed again, and complain about same error lying below :
the data own enough number of gene and the cell in my check ,  It seem like not the filter question but like illegal value within  numpy or pandas,  
Traceback (most recent call last):
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 908, in <module>
    cnmf_obj.consensus(k, args.local_density_threshold, args.local_neighborhood_size, args.show_clustering)
  File "/share/nas1/Data/PipeLine/Other/NMF/NMF-py/v2/bin/cNMF-master/cnmf.py", line 629, in consensus
    cl_dist = squareform(topics_dist[cl_filter, :][:, cl_filter])
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/share/nas1/Data/software/mini_conda/Miniconda3/envs/cNMF-python/lib/python3.7/site-packages/scipy/spatial/distance.py", line 2260, in is_valid_dm
    'symmetric.') % name)
ValueError: Distance matrix 'X' must be symmetric.

The result lying below:
![image](https://user-images.githubusercontent.com/41668708/155256215-1caf569b-bd3b-4ebb-995a-3c6fe7caf57d.png)
cnf_tmp
![image](https://user-images.githubusercontent.com/41668708/155256822-15d03837-8dac-482e-8078-45beb88885cd.png)

Best

**Comment by dylkot** [comment]
Hmm strange, so it is failing after it outputs the final files but before it generates the consensus clustergram plot. How many NMF iterations did you do and how many cells do you have? My guess is that one of the clusters only contains 1 element which might be causing the issue. If you want to, maybe you can share the cnmf_tmp directory with me by e-mail (dkotliar@broadinstitute.org) and I can take a stab at debugging.

**Comment by honghh2018** [comment]
Hi @dylkot ,
     Thanks the help. the data had sent from e-mail curtishongbio@gmail.com.
Best regards
hanhuihong

**Comment by dylkot** [comment]
I don't think I've received an email

**Comment by honghh2018** [comment]
Hi @dylkot ,
   It was so weird, i ensure that i had sent the email.
![1645753063(1)](https://user-images.githubusercontent.com/41668708/155637100-784e9659-11fe-4bdf-b76c-c385320ef3c7.jpg)
   It seem like the e-mail haijacked by Chinese firewall. it was hardly to say, how can i sent this data through other way?

Best

**Comment by honghh2018** [comment]
Hi @dylkot，
     It seem like about the e-mail server  provider problem. i can send the google email @gmail.com successfully.
if you can, to hope altering your e-mail provider with gmail.com, it could be work well

Best,
Hanhuihong

**Comment by dylkot** [comment]
Hi, I got it and will take a look soon! Thank you!

**Comment by dylkot** [comment]
Hi @honghh2018 - the issue should be fixed with the latest push to the github repo and in the latest version of cnmy on pypi (version 1.3.2). You can install the new version with 

```pip install cnmf```

please note that in the new version, you run commands like:

```
cnmf --outdir . --name Luo_T consensus
```

rather than as you were doing before

```
python cnmf.py --outdir . --name Luo_T consensus
```

see the tutorials and README for details. The issue was with the way we were computing euclidean distances between estimated spectra. At times, numerical issues were causing NaNs. In addition, scipy.spatial.distance.squareform was throwing errors due to numerical issues making the matrix non-symmetric and I needed to specify that it shouldn't check for symmetry (checks=False). In any case, let me know if you have any issues getting this to run.

Cheers,
Dylan

**Comment by honghh2018** [comment]
Hi @dylkot ,
     After reinstall the cnmf by pip, the error had solved.
 Thanks
Best
